var Module=(()=>{var _scriptName=globalThis.document?.currentScript?.src;return async function(moduleArg={}){var moduleRtn;var g=moduleArg,aa=!!globalThis.window,p=!!globalThis.WorkerGlobalScope,ba=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type;"undefined"!=typeof __filename?_scriptName=__filename:p&&(_scriptName=self.location.href);var r="",v,w;
if(ba){var fs=require("fs");r=__dirname+"/";w=a=>{a=y(a)?new URL(a):a;return fs.readFileSync(a)};v=async a=>{a=y(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.slice(2)}else if(aa||p){try{r=(new URL(".",_scriptName)).href}catch{}p&&(w=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});v=async a=>{if(y(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=
()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var z=console.error.bind(console),A,ca=!1,y=a=>a.startsWith("file://"),da,ea,B,C,F,G,H,I,fa,J,K,ha,ia=!1;
function ka(){var a=L.buffer;B=new Int8Array(a);F=new Int16Array(a);C=new Uint8Array(a);G=new Uint16Array(a);H=new Int32Array(a);I=new Uint32Array(a);g.HEAPF32=fa=new Float32Array(a);J=new Float64Array(a);K=new BigInt64Array(a);ha=new BigUint64Array(a)}function la(a){g.onAbort?.(a);a="Aborted("+a+")";z(a);ca=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ea?.(a);throw a;}var M;
async function ma(a){if(!A)try{var b=await v(a);return new Uint8Array(b)}catch{}if(a==M&&A)a=new Uint8Array(A);else if(w)a=w(a);else throw"both async and sync fetching of the wasm failed";return a}async function na(a,b){try{var c=await ma(a);return await WebAssembly.instantiate(c,b)}catch(d){z(`failed to asynchronously prepare wasm: ${d}`),la(d)}}
async function oa(a){var b=M;if(!A&&!y(b)&&!ba)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){z(`wasm streaming compile failed: ${d}`),z("falling back to ArrayBuffer instantiation")}return na(b,a)}var pa=a=>{for(;0<a.length;)a.shift()(g)},qa=[],ra=[],sa=()=>{var a=g.preRun.shift();ra.push(a)};class ta{constructor(a){this.P=a-24}}
var ua=0,va=0,O=a=>{for(var b="";;){var c=C[a++];if(!c)return b;b+=String.fromCharCode(c)}},P={},Q={},R={},S=class extends Error{constructor(a){super(a);this.name="BindingError"}},wa=a=>{throw new S(a);};function xa(a,b,c={}){var d=b.name;if(!a)throw new S(`type "${d}" must have a positive integer typeid pointer`);if(Q.hasOwnProperty(a)){if(c.T)return;throw new S(`Cannot register type '${d}' twice`);}Q[a]=b;delete R[a];P.hasOwnProperty(a)&&(b=P[a],delete P[a],b.forEach(e=>e()))}
function T(a,b,c={}){return xa(a,b,c)}
var ya=(a,b,c)=>{switch(b){case 1:return c?d=>B[d]:d=>C[d];case 2:return c?d=>F[d>>1]:d=>G[d>>1];case 4:return c?d=>H[d>>2]:d=>I[d>>2];case 8:return c?d=>K[d>>3]:d=>ha[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},za=[],U=[0,1,,1,null,1,!0,1,!1,1],V=a=>{9<a&&0===--U[a+1]&&(U[a]=void 0,za.push(a))},W=a=>{if(!a)throw new S(`Cannot use deleted val. handle = ${a}`);return U[a]},X=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=
za.pop()||U.length;U[b]=a;U[b+1]=1;return b}};function Aa(a){return this.K(I[a>>2])}
var Ba={name:"emscripten::val",K:a=>{var b=W(a);V(a);return b},N:(a,b)=>X(b),O:Aa,L:null},Ca=(a,b)=>{if(void 0===g[a].M){var c=g[a];g[a]=function(...d){if(!g[a].M.hasOwnProperty(d.length))throw new S(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${g[a].M})!`);return g[a].M[d.length].apply(this,d)};g[a].M=[];g[a].M[c.R]=c}},Da=(a,b,c)=>{if(g.hasOwnProperty(a)){if(void 0===c||void 0!==g[a].M&&void 0!==g[a].M[c])throw new S(`Cannot register public name '${a}' twice`);
Ca(a,a);if(g[a].M.hasOwnProperty(c))throw new S(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);g[a].M[c]=b}else g[a]=b,g[a].R=c},Ea=(a,b,c)=>{switch(b){case 1:return c?function(d){return this.K(B[d])}:function(d){return this.K(C[d])};case 2:return c?function(d){return this.K(F[d>>1])}:function(d){return this.K(G[d>>1])};case 4:return c?function(d){return this.K(H[d>>2])}:function(d){return this.K(I[d>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);
}},Fa=(a,b)=>Object.defineProperty(b,"name",{value:a}),Ha=a=>{a=Ga(a);var b=O(a);Y(a);return b},Ia=(a,b)=>{var c=Q[a];if(void 0===c)throw a=`${b} has unknown type ${Ha(a)}`,new S(a);return c},Ja=(a,b)=>{switch(b){case 4:return function(c){return this.K(fa[c>>2])};case 8:return function(c){return this.K(J[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Ka=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function La(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].L)return!0;return!1}var Ma=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(I[b+4*d>>2]);return c},Na=class extends Error{constructor(a){super(a);this.name="InternalError"}},Oa=[],Ta=(a,b)=>{a=O(a);var c;(c=Oa[b])||(Oa[b]=c=Pa.get(b));if("function"!=typeof c)throw new S(`unknown function pointer with signature ${a}: ${b}`);return c};class Ua extends Error{}
var Va=(a,b)=>{function c(f){e[f]||Q[f]||(R[f]?R[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Ua(`${a}: `+d.map(Ha).join([", "]));},Wa=(a,b)=>{function c(h){h=b(h);if(h.length!==d.length)throw new Na("Mismatched type converter count");for(var m=0;m<d.length;++m)T(d[m],h[m])}var d=[];d.forEach(h=>R[h]=a);var e=Array(a.length),f=[],k=0;for(let [h,m]of a.entries())Q.hasOwnProperty(m)?e[h]=Q[m]:(f.push(m),P.hasOwnProperty(m)||(P[m]=[]),P[m].push(()=>{e[h]=Q[m];++k;k===f.length&&
c(e)}));0===f.length&&c(e)},Xa=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},Ya=(a,b,c)=>{var d=C;if(0<c){c=b+c-1;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);if(127>=f){if(b>=c)break;d[b++]=f}else if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6;d[b++]=128|f&63}else if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12;d[b++]=128|f>>6&63;d[b++]=128|f&63}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63;d[b++]=128|f>>6&63;d[b++]=128|f&63;e++}}d[b]=0}},Za=a=>{for(var b=0,c=0;c<
a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},$a=globalThis.TextDecoder&&new TextDecoder,ab=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},bb=(a=0,b,c)=>{var d=C;b=ab(d,a,b,c);if(16<b-a&&d.buffer&&$a)return $a.decode(d.subarray(a,b));for(c="";a<b;){var e=d[a++];if(e&128){var f=d[a++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var k=d[a++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|d[a++]&63;
65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},cb=globalThis.TextDecoder?new TextDecoder("utf-16le"):void 0,db=(a,b,c)=>{a>>=1;b=ab(G,a,b/2,c);if(16<b-a&&cb)return cb.decode(G.subarray(a,b));for(c="";a<b;++a)c+=String.fromCharCode(G[a]);return c},eb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)F[b>>1]=a.charCodeAt(e),b+=2;F[b>>1]=0;return b-d},fb=a=>2*a.length,
gb=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=I[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},hb=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;H[b>>2]=f;b+=4;if(b+4>c)break}H[b>>2]=0;return b-d},ib=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},jb=[],kb=a=>{var b=jb.length;jb.push(a);return b},lb=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Ia(I[b+4*d>>2],`parameter ${d}`);
return c},mb=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(I[b>>2]=X(d));return a},nb={},ob=a=>{var b=nb[a];return void 0===b?O(a):b},pb=[],tb=(a,b,c,d)=>{var e={string:l=>{var q=0;if(null!==l&&void 0!==l&&0!==l){q=Za(l)+1;var D=qb(q);Ya(l,D,q);q=D}return q},array:l=>{var q=qb(l.length);B.set(l,q);return q}};a=g["_"+a];var f=[],k=0;if(d)for(var h=0;h<d.length;h++){var m=e[c[h]];m?(0===k&&(k=rb()),f[h]=m(d[h])):f[h]=d[h]}c=a(...f);return c=function(l){0!==k&&sb(k);return"string"===b?l?bb(l):"":"boolean"===
b?!!l:l}(c)};g.printErr&&(z=g.printErr);g.wasmBinary&&(A=g.wasmBinary);if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.shift()();g.ccall=tb;g.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?g["_"+a]:(...f)=>tb(a,b,c,f,d)};
var ub={8752:a=>{console.error("Canvas not found:",a?bb(a):"")},8810:(a,b,c)=>{console.log("Trim update: handle="+a+", start="+b+", end="+c)}},vb,Ga,Y,sb,qb,rb,L,Pa,wb={t:(a,b,c)=>{var d=new ta(a);I[d.P+16>>2]=0;I[d.P+4>>2]=b;I[d.P+8>>2]=c;ua=a;va++;throw ua;},u:()=>la(""),q:(a,b,c,d,e)=>{b=O(b);d=0n===d;let f=k=>k;if(d){const k=8*c;f=h=>BigInt.asUintN(k,h);e=f(e)}T(a,{name:b,K:f,N:(k,h)=>{"number"==typeof h&&(h=BigInt(h));return h},O:ya(b,c,!d),L:null})},y:(a,b,c,d)=>{b=O(b);T(a,{name:b,K:function(e){return!!e},
N:function(e,f){return f?c:d},O:function(e){return this.K(C[e])},L:null})},w:a=>T(a,Ba),A:(a,b,c,d)=>{function e(){}b=O(b);e.values={};T(a,{name:b,constructor:e,K:function(f){return this.constructor.values[f]},N:(f,k)=>k.value,O:Ea(b,c,d),L:null});Da(b,e)},k:(a,b,c)=>{var d=Ia(a,"enum");b=O(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Fa(`${d.name}_${b}`,function(){})}});a.values[c]=d;a[b]=d},p:(a,b,c)=>{b=O(b);T(a,{name:b,K:d=>d,N:(d,e)=>e,O:Ja(b,
c),L:null})},g:(a,b,c,d,e,f,k)=>{var h=Ma(b,c);a=O(a);a=Xa(a);e=Ta(d,e);Da(a,function(){Va(`Cannot call ${a} due to unbound types`,h)},b-1);Wa(h,m=>{var l=[m[0],null].concat(m.slice(1));m=a;var q=a;var D=e,n=l.length;if(2>n)throw new S("argTypes array size mismatch! Must at least get return value and 'this' types!");var E=null!==l[1]&&!1,N=La(l),Qa=!l[0].S,t=l[0],x=l[1];D=[q,wa,D,f,Ka,t.K.bind(t),x?.N.bind(x)];for(t=2;t<n;++t)x=l[t],D.push(x.N.bind(x));if(!N)for(t=E?1:2;t<l.length;++t)null!==l[t].L&&
D.push(l[t].L);N=La(l);t=l.length-2;var u=[];x=["fn"];E&&x.push("thisWired");for(n=0;n<t;++n)u.push(`arg${n}`),x.push(`arg${n}Wired`);u=u.join(",");x=x.join(",");u=`return function (${u}) {\n`;N&&(u+="var destructors = [];\n");var Ra=N?"destructors":"null",ja="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");E&&(u+=`var thisWired = toClassParamWire(${Ra}, this);\n`);for(n=0;n<t;++n){var Sa=`toArg${n}Wire`;u+=`var arg${n}Wired = ${Sa}(${Ra}, arg${n});\n`;
ja.push(Sa)}u+=(Qa||k?"var rv = ":"")+`invoker(${x});\n`;if(N)u+="runDestructors(destructors);\n";else for(n=E?1:2;n<l.length;++n)E=1===n?"thisWired":"arg"+(n-2)+"Wired",null!==l[n].L&&(u+=`${E}_dtor(${E});\n`,ja.push(`${E}_dtor`));Qa&&(u+="var ret = fromRetWire(rv);\nreturn ret;\n");l=(new Function(ja,u+"}\n"))(...D);q=Fa(q,l);l=b-1;if(!g.hasOwnProperty(m))throw new Na("Replacing nonexistent public symbol");void 0!==g[m].M&&void 0!==l?g[m].M[l]=q:(g[m]=q,g[m].R=l);return[]})},j:(a,b,c,d,e)=>{b=O(b);
let f=h=>h;if(0===d){var k=32-8*c;f=h=>h<<k>>>k;e=f(e)}T(a,{name:b,K:f,N:(h,m)=>m,O:ya(b,c,0!==d),L:null})},i:(a,b,c)=>{function d(f){return new e(B.buffer,I[f+4>>2],I[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=O(c);T(a,{name:c,K:d,O:d},{T:!0})},x:(a,b)=>{b=O(b);T(a,{name:b,K(c){var d=(d=c+4)?bb(d,I[c>>2],!0):"";Y(c);return d},N(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;
if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new S("Cannot pass non-string to std::string");var f=e?Za(d):d.length;var k=vb(4+f+1),h=k+4;I[k>>2]=f;e?Ya(d,h,f+1):C.set(d,h);null!==c&&c.push(Y,k);return k},O:Aa,L(c){Y(c)}})},m:(a,b,c)=>{c=O(c);if(2===b){var d=db;var e=eb;var f=fb}else d=gb,e=hb,f=ib;T(a,{name:c,K:k=>{var h=d(k+4,I[k>>2]*b,!0);Y(k);return h},N:(k,h)=>{if("string"!=typeof h)throw new S(`Cannot pass non-string to C++ string type ${c}`);var m=f(h),l=vb(4+m+b);I[l>>2]=m/
b;e(h,l+4,m+b);null!==k&&k.push(Y,l);return l},O:Aa,L(k){Y(k)}})},z:(a,b)=>{b=O(b);T(a,{S:!0,name:b,K:()=>{},N:()=>{}})},e:(a,b,c)=>{var [d,...e]=lb(a,b);b=d.N.bind(d);var f=e.map(m=>m.O.bind(m));a--;var k={toValue:W};a=f.map((m,l)=>{var q=`argFromPtr${l}`;k[q]=m;return`${q}(args${l?"+"+8*l:""})`});switch(c){case 0:var h="toValue(handle)";break;case 2:h="new (toValue(handle))";break;case 3:h="";break;case 1:k.getStringOrSymbol=ob,h="toValue(handle)[getStringOrSymbol(methodName)]"}h+=`(${a})`;d.S||
(k.toReturnWire=b,k.emval_returnValue=mb,h=`return emval_returnValue(toReturnWire, destructorsRef, ${h})`);h=`return function (handle, methodName, destructorsRef, args) {\n  ${h}\n  }`;c=(new Function(Object.keys(k),h))(...Object.values(k));h=`methodCaller<(${e.map(m=>m.name)}) => ${d.name}>`;return kb(Fa(h,c))},a:V,s:a=>{if(!a)return X(globalThis);a=ob(a);return X(globalThis[a])},l:(a,b)=>{a=W(a);b=W(b);return X(a[b])},b:a=>{9<a&&(U[a+1]+=1)},d:(a,b,c,d,e)=>jb[a](b,c,d,e),o:()=>X([]),f:a=>X(ob(a)),
n:()=>X({}),c:a=>{var b=W(a);Ka(b);V(a)},h:(a,b,c)=>{a=W(a);b=W(b);c=W(c);a[b]=c},r:(a,b,c)=>{pb.length=0;for(var d;d=C[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;pb.push(112==d?I[c>>2]:106==d?K[c>>3]:105==d?H[c>>2]:J[c>>3]);c+=e?8:4}return ub[a](...pb)},v:a=>{var b=C.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-L.buffer.byteLength+65535)/65536|0;try{L.grow(d);ka();var e=1;
break a}catch(f){}e=void 0}if(e)return!0}return!1}},Z;Z=await (async function(){function a(c){c=Z=c.exports;vb=g._malloc=c.E;Ga=c.F;Y=g._free=c.G;sb=c.H;qb=c.I;rb=c.J;L=c.B;Pa=c.D;ka();return Z}var b={a:wb};if(g.instantiateWasm)return new Promise(c=>{g.instantiateWasm(b,(d,e)=>{c(a(d,e))})});M??=g.locateFile?g.locateFile("main.wasm",r):r+"main.wasm";return a((await oa(b)).instance)}());
(function(){function a(){g.calledRun=!0;if(!ca){ia=!0;Z.C();da?.(g);g.onRuntimeInitialized?.();if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();qa.push(b)}pa(qa)}}if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)sa();pa(ra);g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);a()},1)):a()})();ia?moduleRtn=g:moduleRtn=new Promise((a,b)=>{da=a;ea=b});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=Module;module.exports.default=Module}else if(typeof define==="function"&&define["amd"])define([],()=>Module);
